import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/colors">Colors</Link>
        </li>
        <li>
          <Link to="/typography">Typography</Link>
        </li>
        <li>
          <Link to="/icons">Icons</Link>
        </li>
        <li>
          <Link to="/listitems">Listitems</Link>
        </li>
        <li>
          <Link to="/tables">Tables</Link>
        </li>
        <li>
          <Link to="/sections">Sections</Link>
        </li>
        <li>
          <Link to="/graphs">Graphs</Link>
        </li>
        <li>
          <Link to="/generalnavigation">GeneralNavigation</Link>
        </li>
        <li>
          <Link to="/buttons">Buttons</Link>
        </li>
        <li>
          <Link to="/general">General</Link>
        </li>
        <li>
          <Link to="/dashboardscreendefault">DashboardScreenDefault</Link>
        </li>
        <li>
          <Link to="/dashboardssmarthome">DashboardsSmartHome</Link>
        </li>
        <li>
          <Link to="/dashboardscreencrm">DashboardScreenCRM</Link>
        </li>
        <li>
          <Link to="/dashboardscreencharts">DashboardScreenCharts</Link>
        </li>
        <li>
          <Link to="/applicationskanban">ApplicationsKanban</Link>
        </li>
        <li>
          <Link to="/applicationswizzardone">ApplicationsWizzardOne</Link>
        </li>
        <li>
          <Link to="/applicationsdatatables">ApplicationsDataTables</Link>
        </li>
        <li>
          <Link to="/applicationscalendar">ApplicationsCalendar</Link>
        </li>
        <li>
          <Link to="/applicationsanalytics">ApplicationsAnalytics</Link>
        </li>
        <li>
          <Link to="/dashboardsautomotive">DashboardsAutomotive</Link>
        </li>
        <li>
          <Link to="/dashboardscreenprofileoverview">
            DashboardScreenProfileOverview
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenteams">DashboardScreenTeams</Link>
        </li>
        <li>
          <Link to="/dashboardscreenallprojects">
            DashboardScreenAllProjects
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenreports">DashboardScreenReports</Link>
        </li>
        <li>
          <Link to="/dashboardscreennewuser">DashboardScreenNewUser</Link>
        </li>
        <li>
          <Link to="/dashboardscreenaccountbilling">
            DashboardScreenAccountBilling
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenaccountinvoice">
            DashboardScreenAccountInvoice
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenaccountsecurity">
            DashboardScreenAccountSecurity
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenprojectsgeneral">
            DashboardScreenProjectsGeneral
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenprojectstimeline">
            DashboardScreenProjectsTimeline
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenprojectsnewproject">
            DashboardScreenProjectsNewProject
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenpricing">DashboardScreenPricing</Link>
        </li>
        <li>
          <Link to="/dashboardscreenpagesmessages">
            DashboardScreenPagesMessages
          </Link>
        </li>
        <li>
          <Link to="/dashboardscreenwidgets">DashboardScreenWidgets</Link>
        </li>
        <li>
          <Link to="/sweetalerts">SweetAlerts</Link>
        </li>
        <li>
          <Link to="/dashboardscreenalerts">DashboardScreenAlerts</Link>
        </li>
        <li>
          <Link to="/ecommerceoverview">EcommerceOverview</Link>
        </li>
        <li>
          <Link to="/ecommercenewproductone">EcommerceNewProductOne</Link>
        </li>
        <li>
          <Link to="/ecommerceeditproduct">EcommerceEditproduct</Link>
        </li>
        <li>
          <Link to="/ecommerceproductpage">EcommerceProductPage</Link>
        </li>
        <li>
          <Link to="/ecommerceproductslist">EcommerceProductsList</Link>
        </li>
        <li>
          <Link to="/ecommerceorderlist">EcommerceOrderList</Link>
        </li>
        <li>
          <Link to="/ecommerceorderdetails">EcommerceOrderDetails</Link>
        </li>
        <li>
          <Link to="/ecommercereferral">EcommerceReferral</Link>
        </li>
        <li>
          <Link to="/signinbasic">SigninBasic</Link>
        </li>
        <li>
          <Link to="/signincover">SignInCover</Link>
        </li>
        <li>
          <Link to="/signinillustration">SignInIllustration</Link>
        </li>
        <li>
          <Link to="/applicationswizzardtwo">ApplicationsWizzardTwo</Link>
        </li>
        <li>
          <Link to="/signupbasic">SignupBasic</Link>
        </li>
        <li>
          <Link to="/signupcover">SignUpCover</Link>
        </li>
        <li>
          <Link to="/signupillustration">SignupIllustration</Link>
        </li>
        <li>
          <Link to="/ecommercenewproducttwo">EcommerceNewProductTwo</Link>
        </li>
        <li>
          <Link to="/applicationswizzardthree">ApplicationsWizzardThree</Link>
        </li>
        <li>
          <Link to="/restbasic">RestBasic</Link>
        </li>
        <li>
          <Link to="/resetcover">ResetCover</Link>
        </li>
        <li>
          <Link to="/resetillustration">ResetIllustration</Link>
        </li>
        <li>
          <Link to="/ecommercenewproductthree">EcommerceNewProductThree</Link>
        </li>
        <li>
          <Link to="/lockbasic">LockBasic</Link>
        </li>
        <li>
          <Link to="/signupcoverone">SignUpCoverOne</Link>
        </li>
        <li>
          <Link to="/signupillustrationone">SignupIllustrationOne</Link>
        </li>
        <li>
          <Link to="/ecommercenewproductfour">EcommerceNewProductFour</Link>
        </li>
        <li>
          <Link to="/stepbasic">StepBasic</Link>
        </li>
        <li>
          <Link to="/stepcover">StepCover</Link>
        </li>
        <li>
          <Link to="/signinillustrationone">SignInIllustrationOne</Link>
        </li>
        <li>
          <Link to="/authenticationscreenerror404">
            AuthenticationScreenError404
          </Link>
        </li>
        <li>
          <Link to="/authenticationscreenerror500">
            AuthenticationScreenError500
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
